{"uuid":"1b8c5168-4fcd-484c-a2c8-ee41008e0e99","historyId":"5bf3bff7b7989ecda57d20ff6052f2ac","fullName":"AutomateMakeen.TestPages.TC_LoginPage.tc_loginWithRememberMe","labels":[{"name":"package","value":"AutomateMakeen.TestPages.TC_LoginPage"},{"name":"testClass","value":"AutomateMakeen.TestPages.TC_LoginPage"},{"name":"testMethod","value":"tc_loginWithRememberMe"},{"name":"parentSuite","value":"Employee page test Suite"},{"name":"suite","value":"Employee Test"},{"name":"subSuite","value":"AutomateMakeen.TestPages.TC_LoginPage"},{"name":"host","value":"F4P4W5"},{"name":"thread","value":"27100@F4P4W5.TestNG-test-Employee Test-1(39)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"tc_loginWithRememberMe","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [2562562] but found [0342169]","trace":"java.lang.AssertionError: expected [2562562] but found [0342169]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat AutomateMakeen.TestPages.TC_LoginPage.tc_loginWithRememberMe(TC_LoginPage.java:36)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\r\n\tat java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java)\r\n\tat --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)\r\n\tat java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:151)\r\n\tat org.testng.internal.thread.graph.TestNGFutureTask.<init>(TestNGFutureTask.java:15)\r\n\tat org.testng.internal.thread.graph.GraphOrchestrator.runNodes(GraphOrchestrator.java:58)\r\n\tat org.testng.internal.thread.graph.GraphOrchestrator.run(GraphOrchestrator.java:46)\r\n\tat org.testng.TestTaskExecutor.execute(TestTaskExecutor.java:69)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:720)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1739798594521,"stop":1739798624446}